# Generated by Django 3.0.6 on 2021-02-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(max_length=64)),
                ('CostPrice', models.FloatField()),
                ('Country', models.CharField(max_length=64)),
                ('ORD_DATE', models.DateField()),
                ('ORD_DESCRIPTION', models.TextField()),
                ('Discount', models.FloatField()),
                ('Sellingprice', models.FloatField()),
            ],
        ),
    ]
